# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    totp:
        enabled: true
        issuer: '%env(APP_NAME)%'
        server_name: '%env(APP_NAME)%'
        template: auth/2fa.html.twig
    email:
        enabled: true
        sender_email: '%env(MAILER_FROM_ADDRESS)%'
        sender_name: '%env(MAILER_FROM_NAME)%'
        digits: 6
        template: auth/2fa_email.html.twig
    backup_codes:
        enabled: true
        manager: App\Security\BackupCodeManager
